# render.yaml

services:
  # ──────────────────────────
  # Public entrypoint (NGINX)
  # ──────────────────────────
  - name: zammad-nginx
    type: web
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    dockerCommand: bash -lc 'export NGINX_PORT=${PORT}; exec zammad-nginx'
    plan: standard
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: NGINX_SERVER_SCHEME
        value: https
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString
      - fromGroup: zammad-common
    disk:
      name: zammad-storage
      mountPath: /opt/zammad/storage
      sizeGB: 40
    # Fail fast if required envs aren’t set, then run init.
    preDeployCommand: >
      bash -lc '
        set -euo pipefail
        req=(POSTGRESQL_HOST POSTGRESQL_USER POSTGRESQL_PASS POSTGRESQL_DB
             ELASTICSEARCH_HOST ELASTICSEARCH_USER ELASTICSEARCH_PASS
             ZAMMAD_FQDN ZAMMAD_HTTP_TYPE)
        for v in "${req[@]}"; do
          val="${!v:-}"
          if [ -z "$val" ] || [ "$val" = "__REQUIRED__" ]; then
            echo "❌ Missing required env: $v"; exit 2
          fi
        done
        echo "✅ Env looks good; running zammad-init…"
        zammad-init
      '

  # ──────────────────────────
  # Background job scheduler
  # ──────────────────────────
  - name: zammad-scheduler
    type: worker
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    dockerCommand: zammad-scheduler
    plan: standard
    autoDeploy: false
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString
      - fromGroup: zammad-common

  # ──────────────────────────
  # Rails app (internal)
  # ──────────────────────────
  - name: zammad-railsserver
    type: pserv
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    dockerCommand: zammad-railsserver
    plan: standard
    autoDeploy: false
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString
      - fromGroup: zammad-common

  # ──────────────────────────
  # Websocket app (internal)
  # ──────────────────────────
  - name: zammad-websocket
    type: pserv
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    dockerCommand: zammad-websocket
    plan: standard
    autoDeploy: false
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString
      - fromGroup: zammad-common

  # ──────────────────────────
  # Memcached (internal)
  # ──────────────────────────
  - name: zammad-memcached
    type: pserv
    runtime: image
    image:
      url: memcached:1.6.39-alpine
    dockerCommand: memcached -m 256 -o modern
    plan: standard
    autoDeploy: false

  # ──────────────────────────
  # Redis-compatible KV (internal)
  # ──────────────────────────
  - name: zammad-redis
    type: keyvalue
    plan: standard
    ipAllowList: []
    autoDeploy: false

# ───────────────────────────────
# Shared configuration variables
# ───────────────────────────────
envVarGroups:
  - name: zammad-common
    envVars:
      # --- Postgres (Neon) ---
      - key: POSTGRESQL_HOST
        value: "__REQUIRED__"
      - key: POSTGRESQL_PORT
        value: "5432"
      - key: POSTGRESQL_USER
        value: "__REQUIRED__"
      - key: POSTGRESQL_PASS
        value: "__REQUIRED__"
        sync: false        # keep secret in dashboard
      - key: POSTGRESQL_DB
        value: "__REQUIRED__"
      - key: POSTGRESQL_OPTIONS
        value: "?pool=50&sslmode=require"

      # --- Elasticsearch (Elastic Cloud) ---
      - key: ELASTICSEARCH_ENABLED
        value: "true"
      - key: ELASTICSEARCH_SCHEMA
        value: https
      - key: ELASTICSEARCH_HOST
        value: "__REQUIRED__"
      - key: ELASTICSEARCH_PORT
        value: "443"
      - key: ELASTICSEARCH_USER
        value: "__REQUIRED__"
      - key: ELASTICSEARCH_PASS
        value: "__REQUIRED__"
        sync: false        # keep secret in dashboard

      # --- Cache ---
      - key: MEMCACHE_SERVERS
        value: zammad-memcached:11211

      # --- App/general ---
      - key: ZAMMAD_FQDN
        value: "__REQUIRED__"
      - key: ZAMMAD_HTTP_TYPE
        value: https
      - key: TZ
        value: Africa/Addis_Ababa
