services:
  # Redis (managed)
  - name: zammad-redis
    type: keyvalue
    plan: starter
    ipAllowList: []

  # Memcached (internal)
  - name: zammad-memcached
    type: pserv
    runtime: image
    image:
      url: memcached:1.6.39-alpine
    dockerCommand: memcached -m 256 -o modern
    plan: starter
    autoDeploy: false

  # Rails app (internal) — bind to Render's $PORT
  - name: zammad-railsserver
    type: pserv
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    dockerCommand: bash -lc "export RAILS_PORT=${PORT}; exec /usr/local/bin/zammad-railsserver"
    plan: standard
    autoDeploy: false
    envVars:
      - fromGroup: zammad-common
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString
