services:
  # Redis (managed)
  - name: zammad-redis
    type: keyvalue
    plan: starter
    ipAllowList: []

  # Memcached (internal)
  - name: zammad-memcached
    type: pserv
    runtime: image
    image:
      url: memcached:1.6.39-alpine
    dockerCommand: memcached -m 256 -o modern
    plan: starter
    autoDeploy: false

  # Database initialization - runs once to set up Zammad
  - name: zammad-init
    type: pserv
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    dockerCommand: /docker-entrypoint.sh zammad-init
    plan: starter
    autoDeploy: false
    envVars:
      - fromGroup: zammad-common

  # Rails app (internal) — starts after init completes
  - name: zammad-railsserver
    type: pserv
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    dockerCommand: /docker-entrypoint.sh zammad-railsserver
    plan: standard
    autoDeploy: false
    envVars:
      - fromGroup: zammad-common
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString

  # Nginx web server — this is what exposes the port
  - name: zammad-nginx
    type: web
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    dockerCommand: /docker-entrypoint.sh zammad-nginx
    plan: standard
    envVars:
      - fromGroup: zammad-common
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString
      - key: NGINX_PORT
        value: ${PORT}
