services:
  - name: zammad-nginx
    type: web
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    startCommand: bash -lc "export NGINX_PORT=${PORT}; exec /usr/local/bin/zammad-nginx"
    plan: standard
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - fromGroup: zammad-common
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString
    disk:
      name: zammad-storage
      mountPath: /opt/zammad/storage
      sizeGB: 100

  - name: zammad-scheduler
    type: worker
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    startCommand: /usr/local/bin/zammad-scheduler
    plan: starter
    autoDeploy: false
    envVars:
      - fromGroup: zammad-common
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString

  - name: zammad-railsserver
    type: pserv
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    startCommand: /usr/local/bin/zammad-railsserver
    plan: standard
    autoDeploy: false
    envVars:
      - fromGroup: zammad-common
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString

  - name: zammad-websocket
    type: pserv
    runtime: image
    image:
      url: ghcr.io/zammad/zammad:6.5.1
    startCommand: /usr/local/bin/zammad-websocket
    plan: starter
    autoDeploy: false
    envVars:
      - fromGroup: zammad-common
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: zammad-redis
          property: connectionString

  - name: zammad-memcached
    type: pserv
    runtime: image
    image:
      url: memcached:1.6.39-alpine
    startCommand: memcached -m 256 -o modern
    plan: starter
    autoDeploy: false

  - name: zammad-redis
    type: keyvalue
    plan: starter
    ipAllowList: []
